## Map generator
In dit bestand leg ik uit hoe ik maps genereer. Als eerste moet ik een algoritme kiezen om paden te genereren op een 2d map space, deze paden moeten een bepaalde dikte hebben.

- Bronnen:
    - https://theory.stanford.edu/~amitp/GameProgramming/AStarComparison.html
    - https://medium.com/@yvanscher/playing-with-perlin-noise-generating-realistic-archipelagos-b59f004d8401
    - https://www.geeksforgeeks.org/find-whether-path-two-cells-matrix/


Als eerste ben ik begonnen met een map genereren doormiddel van een noise functie, hiermee krijg ik een simpele map die wij als groepje kunnen gebruiken om alvast te proberen om de intergratie werkend te maken. De bedoeling is dat de map in een 2d array komt, deze array heeft verschillende nummers die geassiocieerd worden met verschillende tiles.

In [1]:
import noise
import numpy as np
from PIL import Image
import random
import sys

Voor de eerste versie van de map gebruik ik nu een noise generator, perlin noise, dit gebruik ik om makkelijk te kunnen testen voor de implentmentatie met Unity, de API en de database. De noise generator maakt een value tussen -1 en 1 voor dit project ben ik op zoek naar de values 0 en 1, dus loop ik over de array om te checken in welke catogory dit value past.

In [9]:
map_shape = (100, 200)

scale = 100
octaves = 5
persistence  = 0.5
lacunarity = 2.0

randomness = random.randint(0, 2^32)
print(randomness)
map = np.zeros(map_shape)
for i in range(map_shape[0]):
    for j in range(map_shape[1]):
        map[i][j] = noise.pnoise2(
            i / scale,
            j / scale,
            octaves=octaves,
            persistence=persistence,
            lacunarity=lacunarity,
            base=randomness
        )

def set_map_numbers(map):
    for i in range(len(map)):
        for n in range(len(map[0])):
            if map[i][n] >= 0:
                map[i][n] = 255
            else:
                map[i][n] = 0
    return map

map = set_map_numbers(map)
print("shape of the map: " + str(map.shape))
print("mapdata: " + str(map))

im = Image.fromarray(map)
im.show()

14
shape of the map: (100, 200)
mapdata: [[255. 255. 255. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ... 255. 255. 255.]
 [  0.   0.   0. ... 255. 255.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]


Ik heb ook een functie gemaakt om de array te kunnen visualizen, dit doe ik doormiddel van PILLOW, een library die gemaakt is voor het maken, manipuleren en opslaan van images.